all:
 vars:
   ansible_user: centos
   ansible_ssh_private_key_file: ~/Documents/Cours/M2/DevOpsTPs/.ssh/id_rsa
   docker_network_name: my-network
 children:
   prod:
     hosts: lcambillau.takima.cloud