- hosts: all
  gather_facts: false
  become: yes

  roles:
    - role: docker
      vars:
          ansible_python_interpreter: /usr/bin/python
    - role: network
      vars:
        ansible_python_interpreter: /usr/bin/python3
    - role: database
    - role: app
    - role: proxy
    - role: front