name: CI devops 2023 - Build and push

on:
  workflow_run:
    workflows: 
    - CI devops 2023 - Test backend
    branches: 
    - main
    types: 
    - completed

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    runs-on: ubuntu-22.04

  # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        # run only when code is compiling and tests are passing
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./simple-api
          # Note: tags has to be all lower-case
          tags:  ${{ secrets.DOCKERHUB_USERNAME }}/simple-api
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./database
          # Note: tags has to be all lower-case
          tags:  ${{ secrets.DOCKERHUB_USERNAME }}/database
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./HTTP_Server
          # Note: tags has to be all lower-case
          tags:  ${{ secrets.DOCKERHUB_USERNAME }}/httpd
          push: ${{ github.ref == 'refs/heads/main' }}